---
AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.1

Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120

Layout/IndentArray:
  EnforcedStyle: consistent

Layout/IndentHash:
  EnforcedStyle: consistent

Layout/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space

Style/AndOr:
  EnforcedStyle: conditionals

Style/FrozenStringLiteralComment:
  EnforcedStyle: always
  Exclude:
    - Gemfile
    - Rakefile
    - '*.gemspec'

Style/GlobalVars:
  Exclude:
    - ext/quirc/extconf.rb

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
